NET.W.2018.Kalinina.25/BankWebApplication/Models/BankAccountViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using BLL.Interface.Entities;

namespace BankWebApplication.Models
{
    public class BankAccountViewModel
    {
        public IEnumerable<BankAccount> AccountsList { get; set; }
    }
}

NET.W.2018.Kalinina.25/BankWebApplication/Controllers/CloseAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BankWebApplication.Controllers
{
    public class CloseAccountController : Controller
    {
        public ActionResult Close(string AccountID)
        {
            TempData["Id"] = Url.RequestContext.RouteData.Values["id"];
            TempData.Keep();
            return View();
        }

        [HttpPost]
        public RedirectToRouteResult Close()
        {
            string accountNumber = TempData["Id"].ToString();
            HomeController.service.CloseAccount(accountNumber);
            return RedirectToAction("Index", "Home"); ;
        }
    }
}

NET.W.2018.Kalinina.25/BankWebApplication/Controllers/DepositController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BankWebApplication.Controllers
{
    public class DepositController : Controller
    {
        public ActionResult Deposit(string AccountID)
        {
            TempData["Id"] = Url.RequestContext.RouteData.Values["id"];
            TempData.Keep();
            return View();
        }

        [HttpPost]
        public RedirectToRouteResult Deposit(decimal depositAmount)
        {
            HomeController.service.DepositMoney(TempData["Id"].ToString(), (decimal)depositAmount);
            return RedirectToAction("Index", "Home");
        }
    }
}

NET.W.2018.Kalinina.25/BankWebApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL.Interface.Entities;
using BLL.Interface.Interfaces;
using DependencyResolver;
using Ninject;
using BankWebApplication.Models;

namespace BankWebApplication.Controllers
{
    public class HomeController : Controller
    {
        private static readonly IKernel resolver;

        public static IAccountService service;

        static HomeController()
        {
            resolver = new StandardKernel();
            resolver.ConfigurateResolver();

            service = resolver.Get<IAccountService>();
        }

        public ActionResult Index()
        {
            var accounts = service.GetAccounts();

            ViewBag.Accounts = accounts;

            return View();
        }
    }
}

NET.W.2018.Kalinina.25/BankWebApplication/Controllers/OpenAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL.Interface.Entities;

namespace BankWebApplication.Controllers
{
    public class OpenAccountController : Controller
    {
        public ActionResult Open()
        {
            return View();
        }

        [HttpPost]
        public RedirectToRouteResult Open(string accountNumber, string firstName, string lastName, int accountType)
        {
            HomeController.service.OpenAccount(lastName, firstName, accountNumber, 0, 0, (AccountType)accountType);
            return RedirectToAction("Index", "Home");
        }
    }
}

NET.W.2018.Kalinina.25/BankWebApplication/Controllers/TransferController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BankWebApplication.Controllers
{
    public class TransferController : Controller
    {
        public ActionResult Transfer(string AccountID)
        {
            TempData["Id"] = Url.RequestContext.RouteData.Values["id"];
            TempData.Keep();
            return View();
        }

        [HttpPost]
        public RedirectToRouteResult Transfer(string secondAccountID, decimal? transferAmount)
        {
            string accountNumber = TempData["Id"].ToString();
            HomeController.service.TransferMoney(accountNumber, secondAccountID, (decimal)transferAmount);
            return RedirectToAction("Index", "Home");
        }
    }
}

NET.W.2018.Kalinina.25/BankWebApplication/Controllers/WithdrawController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BankWebApplication.Controllers
{
    public class WithdrawController : Controller
    {
        public ActionResult Withdraw(string AccountID)
        {
            TempData["Id"] = Url.RequestContext.RouteData.Values["id"];
            TempData.Keep();
            return View();
        }

        [HttpPost]
        public RedirectToRouteResult Withdraw(decimal withdrawAmount)
        {
            HomeController.service.WithdrawMoney(TempData["Id"].ToString(), (decimal)withdrawAmount);
            return RedirectToAction("Index", "Home");
        }
    }
}

NET.W.2018.Kalinina.25/BankWebApplication/Views/CloseAccount/Close.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Close account</title>
</head>
<body>
    <div>
        <form action="/CloseAccount/Close" method="post">
            <p />
            <h1>Закрыть счет?</h1></p>
            <input type="submit" value="Close" />
        </form>
    </div>
</body>

NET.W.2018.Kalinina.25/BankWebApplication/Views/Deposit/Deposit.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Deposit money</title>
</head>
<body>
    <div>
        <form action="/Deposit/Deposit" method="post">
            <p />
            Deposit amount  <input type="number" name="depositAmount" min="0" step="0.01" required /> <p />
            <input type="submit" value="Deposit" />
        </form>
    </div>
</body>

NET.W.2018.Kalinina.25/BankWebApplication/Views/Home/Close.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Close account</title>
</head>
<body>
    <div>
        <form action="/Home/Close" method="post">
            Закрыть счет?
            <table>
                <tr><td><input type="submit" value="Close" /> </td><td></td></tr>
            </table>
        </form>
    </div>
</body>
</html>

NET.W.2018.Kalinina.25/BankWebApplication/Views/Home/Deposit.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Deposit money</title>
</head>
<body>
    <div>
        <form action="/Home/Deposit" method="post">
            <table>
                <tr>
                    <td>Deposit amount  <input type="number" name="depositAmount" min="0" step="0.01" /> </td>
                </tr>
                <tr><td><input type="submit" value="Deposit" /> </td><td></td></tr>
            </table>
        </form>
    </div>
</body>
</html>

NET.W.2018.Kalinina.25/BankWebApplication/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using BLL.Interface.Entities;
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Банк</title>
</head>
<body>
    <div>
        <h3>Bank Accounts</h3>
        <a href="/OpenAccount/Open">Open new bank account</a> <p/>
        <table cellpadding="12">
            <tr>
                <td width="100"><p>ID</p></td>
                <td width="150"><p>Owner</p></td>
                <td width="150"><p>Invoice Amount</p></td>
                <td width="100"><p>Account Type</p></td>
                <td width="100"><p>Bonus Scores</p></td>
                <td width="100"><p>Is Closed</p></td>
                <td></td>
            </tr>
            @foreach (var b in ViewBag.Accounts)
            {
                <tr>
                    @{
                        string accountType = string.Empty;
                        if (b.GetType() == typeof(BaseAccount))
                        {
                            accountType = "Base";
                        }
                        else if (b.GetType() == typeof(GoldAccount))
                        {
                            accountType = "Gold";
                        }
                        else if (b.GetType() == typeof(PlatinumAccount))
                        {
                            accountType = "Platinum";
                        }
                    }
                    <td><p>@b.AccountID</p></td>
                    <td><p>@b.Owner.FirstName @b.Owner.LastName</p></td>
                    <td><p>@b.InvoiceAmount</p></td>
                    <td><p>@accountType</p></td>
                    <td><p>@b.BonuseScores</p></td>
                    <td><p>@b.IsClosed</p></td>
                    <td width="100"><p><a href="/Deposit/Deposit/@b.AccountID">Deposit</a></p></td>
                    <td width="100"><p><a href="/Withdraw/Withdraw/@b.AccountID">Withdraw</a></p></td>
                    <td width="100"><p><a href="/Transfer/Transfer/@b.AccountID">Transfer</a></p></td>
                    <td width="100"><p><a href="/CloseAccount/Close/@b.AccountID">Close</a></p></td>
                </tr>
            }
        </table>
    </div>
</body>

NET.W.2018.Kalinina.25/BankWebApplication/Views/Home/Transfer.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Transfer money</title>
</head>
<body>
    <div>
        <form action="/Home/Transfer" method="post">
            <table>
                <tr>
                    <td>Account number    <input type="text" name="secondAccountID"/> </td>
                </tr>
                <tr>
                    <td>Transfer Amount <input type="number" name="transferAmount" min="0" step="0.01" /> </td>
                </tr>
                <tr><td><input type="submit" value="Transfer" /> </td><td></td></tr>
            </table>
        </form>
    </div>
</body>
</html>

NET.W.2018.Kalinina.25/BankWebApplication/Views/Home/Withdraw.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Withdraw money</title>
</head>
<body>
    <div>
        <form action="/Home/Withdraw" method="post">
            <table>
                <tr>
                    <td>Withdraw amount  <input type="number" name="withdrawAmount" min="0" step="0.01" /> </td>
                </tr>
                <tr><td><input type="submit" value="Withdraw" /> </td><td></td></tr>
            </table>
        </form>
    </div>
</body>
</html>

NET.W.2018.Kalinina.25/BankWebApplication/Views/OpenAccount/Open.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Open account</title>
</head>
<body>
    <div>
        <form action="/OpenAccount/Open" method="post">
            <p />
            First name  <input type="text" name="firstName" required pattern="[A-ZА-Яа-яa-z]+" /> <p />
            Last name  <input type="text" name="lastName" required pattern="[A-ZА-Яа-яa-z]+" /> <p />
            Account number  <input type="text" name="accountNumber" required pattern="[A-Z0-9]{6}" /><p />


            Account type <select name="accountType" size="1" required>
                <option value="0">Base</option>
                <option value="1">Gold</option>
                <option value="2">Platinum</option>
            </select><p />
            <input type="submit" value="Open" />

        </form>
    </div>
</body>

NET.W.2018.Kalinina.25/BankWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – Bank Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Bank Application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home page", "Index", "Home")</li>
                    <li>@Html.ActionLink("Open Account", "Open", "OpenAccount")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – Bank Account</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

NET.W.2018.Kalinina.25/BankWebApplication/Views/Transfer/Transfer.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Transfer money</title>
</head>
<body>
    <div>
        <form action="/Transfer/Transfer" method="post">
            <p />
            Account number    <input type="text" required name="secondAccountID" /><p />
            Transfer Amount <input type="number" required name="transferAmount" min="0" step="0.01" /><p />
            <input type="submit" value="Transfer" />
        </form>
    </div>
</body>

NET.W.2018.Kalinina.25/BankWebApplication/Views/Withdraw/Withdraw.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Withdraw money</title>
</head>
<body>
    <div>
        <form action="/Withdraw/Withdraw" method="post">
            <p />
            Withdraw amount  <input type="number" required name="withdrawAmount" min="0" step="0.01" /><p />
            <input type="submit" value="Withdraw" />
        </form>
    </div>
</body>